### PR TITLE
add logging support and other minor fixes

### PR DESCRIPTION
**Pull request by brc**
- bugfix: use `args` attribute to access exception message tuple
  ( otherwise the exception handling code fails with:
        `'RequestException' object has no attribute 'message'` )
- use `logging.debug()` for every method
- DRY up some API URLs and debug messages
- fix some copy/paste artifacts in method signatures and docstrings
- format return statements with a consistent style that Chad prefers

### CODE REVIEW

**Comment by brc** [comment]
This is a big change to review;
it was hours and hours of work.

There are probably things you will hate. :grin: 
Many log messages were kept terse to stay within 79 cols.
I double-checked my work and was as careful as possible.

**Comment by brc** [comment]
``` bash
archie:/git/invsblduck/ecsminion> python2 -B -m compileall ecsminion
Listing . ...
Compiling ./__init__.py ...
Listing ./api ...
Compiling ./api/__init__.py ...
Compiling ./api/authentication.py ...
Listing ./api/configuration ...
Compiling ./api/configuration/__init__.py ...
Compiling ./api/configuration/certificate.py ...
Compiling ./api/configuration/configuration_properties.py ...
Compiling ./api/configuration/licensing.py ...
Listing ./api/geo_replication ...
Compiling ./api/geo_replication/__init__.py ...
Compiling ./api/geo_replication/replication_group.py ...
Compiling ./api/geo_replication/temporary_failed_zone.py ...
Listing ./api/metering ...
Compiling ./api/metering/__init__.py ...
Compiling ./api/metering/billing.py ...
Listing ./api/monitoring ...
Compiling ./api/monitoring/__init__.py ...
Compiling ./api/monitoring/capacity.py ...
Compiling ./api/monitoring/dashboard.py ...
Compiling ./api/monitoring/events.py ...
Listing ./api/multitenancy ...
Compiling ./api/multitenancy/__init__.py ...
Compiling ./api/multitenancy/namespace.py ...
Listing ./api/provisioning ...
Compiling ./api/provisioning/__init__.py ...
Compiling ./api/provisioning/base_url.py ...
Compiling ./api/provisioning/bucket.py ...
Compiling ./api/provisioning/data_store.py ...
Compiling ./api/provisioning/node.py ...
Compiling ./api/provisioning/storage_pool.py ...
Compiling ./api/provisioning/virtual_data_center.py ...
Listing ./api/support ...
Compiling ./api/support/__init__.py ...
Compiling ./api/support/call_home.py ...
Listing ./api/undocumented ...
Compiling ./api/undocumented/__init__.py ...
Compiling ./api/undocumented/user_info.py ...
Listing ./api/user_management ...
Compiling ./api/user_management/__init__.py ...
Compiling ./api/user_management/authentication_provider.py ...
Compiling ./api/user_management/secret_key.py ...
Compiling ./api/user_management/secret_key_self_service.py ...
Compiling ./api/user_management/user_management.py ...
Compiling ./api/user_management/user_object.py ...
Listing ./util ...
Compiling ./util/__init__.py ...
Compiling ./util/common.py ...
Compiling ./util/exceptions.py ...
Compiling ./util/token_request.py ...
```

**Comment by chadlung** [comment]
If you can add a section to the readme on how new user's can enable the logging that would be great. I understand this helped you out knowing what exactly the library was doing as it was running so makes sense to have this ability to turn up verbosity for others as well.

**Comment by brc** [comment]
Done.  I think it's in pretty good shape for devs to consume.

**Pull request merged**
